apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yluroas3l-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/yluroas3l-java-springboot-gitops